<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VizinhoDAgua.Domain\VizinhoDAgua.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UseCases\Community\Delete\" />
    <Folder Include="UseCases\Community\GetAll\" />
    <Folder Include="UseCases\Community\GetById\" />
    <Folder Include="UseCases\Community\Update\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.0" />
    <PackageReference Include="MediatR" Version="13.1.0" />
  </ItemGroup>

</Project>
